# Generated by Django 4.1.7 on 2023-03-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_student_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
