# Generated by Django 4.1.7 on 2023-03-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_grade_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='completed',
            field=models.BooleanField(null=True),
        ),
    ]
