# Generated by Django 4.1.7 on 2023-03-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_grade_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.cohort'),
        ),
    ]
